config = {
    'saved_path':'emis_measure',
    'readme_path':'docs/emis_calculation/README.md',
    'anchor_in_readme': "[place_table_here]: #",
    'url_2324':"https://files.digital.nhs.uk/FC/187D35/health_care_ld_sicbl_2023-24.csv",
    'url_2223':"https://files.digital.nhs.uk/43/BD15AC/health_care_ld_sicbl_2022-23.csv",
    'url_1722':"https://files.digital.nhs.uk/BC/016738/health_care_ld_sicbl_data_1718_2122.zip",
    'url_1621':"https://files.digital.nhs.uk/49/70A43E/health_care_ld_ccg_data_1617_2021.zip",
    'main_link': "https://digital.nhs.uk/data-and-information/publications/statistical/health-and-care-of-people-with-learning-disabilities",
    'file_path_to_save': "docs/emis_calculation/source_files/",
    'file_path_to_emis_measure': "docs/emis_calculation/emis_measure.csv",
    'list_of_csv':{
        '23_24':'health_care_ld_sicbl_2023-24.csv',
        '22_23':'health_care_ld_sicbl_2022-23.csv',
        '21_22':'Health and Care of People with Learning Disabilities SICBL data 2021-22.csv',
        '20_21':'Health and Care of People with Learning Disabilities SICBL data 2020-21.csv',
        '19_20':'Health and Care of People with Learning Disabilities SICBL data 2019-20.csv',
        '18_19':'Health and Care of People with Learning Disabilities SICBL data 2018-19.csv',
        '17_18':'Health and Care of People with Learning Disabilities SICBL data 2017-18.csv',
        '16_17':'Health and Care of People with Learning Disabilities CCG data 2016-17.csv'
    },
    "groupby_index":['YEAR','SEX','AGE_BAND'],
    'numerator' : ['LDOB089','LDOB091'],
    'denominator' : ['LDOB003A' , 'LDOB003B'],
    'all_code' : ['ALL'],
    'sex_rename' : {'F':'female' , 'M':'male'},
    'cols_of_interest': ['YEAR','SEX','INDICATOR','AGE_BAND','VALUE'],
    'rename_col_for_numerator' : {'VALUE': 'numerator'},
    'rename_col_for_denominator' : {'VALUE': 'denominator'},
    'rename_cols_indices': {'SEX':'sex','AGE_BAND':'age_band'},
    'nhs_sex_col': 'SEX',
    'nhs_ageband_col':'AGE_BAND',
    'nhs_indicator_col':'INDICATOR',
    'nhs_vaule_col':'VALUE',
    'nhs_ratio_col':'ratio',
    'nhs_denominator_col':'denominator',
    'nhs_numerator_col':'numerator',
    'interval_start':'interval_start',
    'interval_end':'interval_end',
    'cols_in_opensafely' : [
        'interval_start',
        'interval_end',
        'ratio',
        'numerator',
        'denominator',
        'sex',
        'age_band'
    ],
    'age_band_correction' : {
        '0 to 9':'0 to 9',
        '10 to 13':'10 to 17',
        '14 to 17':'10 to 17',
        '18 to 24':'18 to 24',
        '25 to 34':'25 to 34',
        '35 to 44':'35 to 44',
        '45 to 49':'45 to 54',
        '50 to 54':'45 to 54',
        '55 to 59':'55 to 64',
        '60 to 64':'55 to 64',
        '65 to 69':'65 to 74',
        '70 to 74':'65 to 74',
        '75 and over':'75 and over',
    },
    }
